version: '1.0.0'

services:

    club-database:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_DB: "club_db"
        POSTGRES_USER: "club_user"
        POSTGRES_PASSWORD: "club_password"

    player-database:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_DB: "player_db"
        POSTGRES_USER: "player_user"
        POSTGRES_PASSWORD: "player_password"

    playerMicroservice:
      image: player:0.0.1-SNAPSHOT
      restart: always
      environment:
        SPRING_DATASOURCE_URL: "jdbc:postgresql://player-database:5432/player_db"
        SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
        SPRING_DATASOURCE_USERNAME: "player_user"
        SPRING_DATASOURCE_PASSWORD: "player_password"
        SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"

    clubMicroservice:
      image: club:0.0.1-SNAPSHOT
      restart: always
      environment:
        PLAYERS_MICROSERVICE_URL: "http://playerMicroservice:8080"
        SPRING_DATASOURCE_URL: "jdbc:postgresql://club-database:5432/club_db"
        SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
        SPRING_DATASOURCE_USERNAME: "club_user"
        SPRING_DATASOURCE_PASSWORD: "club_password"
        SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"

    gatewayMicroservice:
      image: gateway:0.0.1-SNAPSHOT
      restart: always
      ports:
        - "8080:8080"
      environment:
        PLAYERS_MICROSERVICE_URL: "http://playerMicroservice:8080"
        CLUBS_MICROSERVICE_URL: "http://clubMicroservice:8080"
        GATEWAY_MICROSERVICE_URL: "localhost:8080"


